name: homework-CI

on:
  push:
    branches:
      - main

jobs:
  My-first-test:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Log in to Docker Hub user ${{ secrets.DOCKERHUB_USERNAME }} pass ${{ secrets.DOCKERHUB_USERNAME }} var.user user ${{ vars.DOCKERHUB_USERNAME }}
            uses: docker/login-action@v2
            with:
              username: 3guol
              password: dckr_pat_9gU5TlYF3-lqR7SYeWqkaGC8ce4

          - name: Build and push image
            uses: docker/build-push-action@v4
            with:
              push: true
              tags: ${{ vars.DOCKERHUB_USERNAME }}/demo-app:latest
          - run: date
