name: homework-CI

on:
  push:
    branches:
      - main

jobs:
  My-first-test:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Log in to Docker Hub user ${{ secrets.DOCKERHUB_USERNAME }} pass ${{ secrets.DOCKERHUB_USERNAME }} var.user user ${{ vars.DOCKERHUB_USERNAME }}
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_USERNAME }}

          - name: Build and push image
            uses: docker/build-push-action@v4
            with:
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:latest
          - run: date
